### ISSUE TITLE
"ImportError: libOMIScriptProvider.so: cannot open shared object file: No such file or directory" for omireg with private build

### ISSUE THREAD

**Issue by JumpingYang001** [Microsoft/omi-script-provider#11]
Issue repro:
```
/samples/xyz_frog
root@py64-cent7-01  #  /opt/omi/bin/omireg --Python XYZ_Frog
Traceback (most recent call last):
  File "client.py", line 7, in <module>
    import omi
ImportError: libOMIScriptProvider.so: cannot open shared object file: No such file or directory
/opt/omi/bin/omireg: MI_Module.schemaDecl is null
```

I tried to run another test and get same error with above omireg:
```
/samples/xyz_frog
root@py64-cent7-01  # python /opt/omi/lib/client.py
Traceback (most recent call last):
  File "/opt/omi/lib/client.py", line 7, in <module>
    import omi
ImportError: libOMIScriptProvider.so: cannot open shared object file: No such file or directory
```

Temporary workaround is `ln -s /opt/omi/lib/libOMIScriptProvider.so /usr/lib; ldconfig`, but we need to fix for package.

**Comment by JumpingYang001** [comment]
Will check it

**Comment by alinbalutoiu** [comment]
This issue has been fixed, please re-open if you encounter it again.
