### ISSUE TITLE
[Design issue] env variable "PYTHONPATH" need to set on omiserver and on omireg

### ISSUE THREAD

**Issue by JumpingYang001** [Microsoft/omi-script-provider#9]
currently, omiserver and omireg need to set env variable "PYTHONPATH" if we want to use python module, for example, https://github.com/Microsoft/omi-script-provider/tree/master/samples/xyz_frog
we need to go to the xyz_frog diretory and run `export PYTHONPATH=`pwd`` on both omiserver and omireg side, otherwise it will show error "ValueError : ERROR: unable to import mi_main" on both side.
Just pick it up.

**Comment by JumpingYang001** [comment]
omiserver is not a normal process, it is a daemond process, so it might be hard to set "PYTHONPATH" env variable when it is running.

**Comment by JumpingYang001** [comment]
if we don't set PYTHONPATH on both side: omiserver and omireg, omireg will get following error:
```
Unhandled exception: <type 'exceptions.ValueError'>
Traceback (most recent call last):
  File "client.py", line 30, in <module>
    sys.exit (main (sys.argv))
  File "client.py", line 19, in main
    client = Client (fd, path)
ValueError: ERROR: unable to import mi_main
/tmp/Build-omi-script-provider/omi/Unix/output/bin/omireg: MI_Module.schemaDecl is null
```

**Comment by JumpingYang001** [comment]
currently, it only support only module name: "mi_main"
https://github.com/Microsoft/omi-script-provider/blob/52c40dbc54a44b0b06359dd9b9d6f3d7893cb32d/python/client_wrapper.cpp#L184

**Comment by JumpingYang001** [comment]
that say, current python script provider only support 1 customized provider wrote by python.
If we omireg multiple provider, it will only 1 works.

**Comment by JumpingYang001** [comment]
the error from omiserver side when I ran `/opt/omi/bin/omicli ei root/cimv2 XYZ_Frog`:
```
2017/09/21 23:01:20 [23950,23950] INFO: null(0): EventId=40012 Priority=INFO Socket: 0x16d8ae0, closing connection (mask 2)
2017/09/21 23:01:20 [23950,23950] WARNING: null(0): EventId=30214 Priority=WARNING Selector_RemoveHandler: selector=0x5d17a8, handler=0x16d8ae0, name=null NOT REGISTERED
2017/09/21 23:01:20 [23949,23949] INFO: null(0): EventId=40028 Priority=INFO Socket: 0x1867d80, Connection Closed while reading header

2017/09/21 23:01:20 [23949,23949] INFO: null(0): EventId=40012 Priority=INFO Socket: 0x1867d80, closing connection (mask 2)
2017/09/21 23:01:20 [23949,23949] INFO: null(0): EventId=40033 Priority=INFO Selector_RemoveHandler: selector=0x5d37e8, handler=0x1867d80, name=BINARY_SERVER_CONNECTION
2017/09/21 23:01:20 [23950,23950] INFO: null(0): EventId=40011 Priority=INFO done with receiving msg(0x16d9548:4099:EnumerateInstancesReq:2711)
2017/09/21 23:01:20 [23950,23950] INFO: null(0): EventId=40032 Priority=INFO Selector_AddHandler: selector=0x5d17a8, handler=0x16dbfd0, name=null
2017/09/21 23:01:20 [23950,23950] INFO: null(0): EventId=40005 Priority=INFO _SendRequestToAgent msg(0x16dca38:15:BinProtocolNotification:1), from original operationId: 0 to 1
2017/09/21 23:01:20 [23950,23950] INFO: null(0): EventId=40005 Priority=INFO _SendRequestToAgent msg(0x16dcf28:4099:EnumerateInstancesReq:2), from original operationId: 2711 to 2
2017/09/21 23:01:20 [23949,23949] INFO: null(0): EventId=40032 Priority=INFO Selector_AddHandler: selector=0x5d37e8, handler=0x1867d80, name=BINARY_SERVER_CONNECTION
2017/09/21 23:01:20 [23949,23949] INFO: null(0): EventId=40011 Priority=INFO done with receiving msg(0x1877c48:36:VerifySocketConn:0)
2017/09/21 23:01:20 [23949,23949] INFO: null(0): EventId=40011 Priority=INFO done with receiving msg(0x1877c48:34:CreateAgentMsg:0)
2017/09/21 23:01:20 [23949,23949] INFO: null(0): EventId=40033 Priority=INFO Selector_RemoveHandler: selector=0x5d37e8, handler=0x1867d80, name=BINARY_SERVER_CONNECTION
2017/09/21 23:01:20 [23949,23949] WARNING: null(0): EventId=30107 Priority=WARNING Sock_Read: Error 9
2017/09/21 23:01:20 [23949,23949] WARNING: null(0): EventId=30112 Priority=WARNING Socket: 0x1867d80, Error: 1 while reading header

2017/09/21 23:01:20 [23949,23949] INFO: null(0): EventId=40012 Priority=INFO Socket: 0x1867d80, closing connection (mask 2)
2017/09/21 23:01:20 [23949,23949] WARNING: null(0): EventId=30214 Priority=WARNING Selector_RemoveHandler: selector=0x5d37e8, handler=0x1867d80, name=BINARY_SERVER_CONNECTION NOT REGISTERED
Unhandled exception: <type 'exceptions.ValueError'>
Traceback (most recent call last):
  File "client.py", line 30, in <module>
    sys.exit (main (sys.argv))
  File "client.py", line 19, in main
    client = Client (fd, path)
ValueError: ERROR: unable to import mi_main
2017/09/21 23:01:20 [23950,23950] INFO: null(0): EventId=40011 Priority=INFO done with receiving msg(0x16dcf28:4:PostResultMsg:2)
2017/09/21 23:01:20 [23950,23950] INFO: null(0): EventId=40028 Priority=INFO Socket: 0x16d7d60, Connection Closed while reading header

2017/09/21 23:01:20 [23950,23950] INFO: null(0): EventId=40012 Priority=INFO Socket: 0x16d7d60, closing connection (mask 2)
2017/09/21 23:01:20 [23950,23950] INFO: null(0): EventId=40033 Priority=INFO Selector_RemoveHandler: selector=0x5d17a8, handler=0x16d7d60, name=BINARY_SERVER_CONNECTION
```

**Comment by JumpingYang001** [comment]
Per Eric, moving the provider to /opt/omi/lib, it works fine, and we needn't PYTHONPATH anymore.
